### ISSUE TITLE
ISSUE_FOR GSOC 2k21

### ISSUE THREAD

**Issue by dhawankrish654** [scorelab/DengueStop#75]
Hey 
I am a GSOC 2k21 aspirant and wanted to contribute to your community. I found this dengue stop application quite useful and solving major issues in countries. I have an idea regarding this application:- why not take this application to android and mobile so that it has a better reach and in place of using it specifically for dengue we can use it for many other pandemics and diseases that are spreading in today's world. Being an android developer I could surely work upon this idea if the mentors allow me.

**Comment by rajitha1998** [comment]
@dhawankrish654  as to my knowledge currently dengue stop is mobile compatible. It is developed using Flutter which supports both Android and iOS.

**Comment by dhawankrish654** [comment]
Okay thank you
